### ISSUE TITLE
Problems fingering ganglia...

### ISSUE THREAD

**Issue by JamesOwers** [cdt-data-science/serverwatch#1]
Hullo! Had a crack at running this on self managed machine. Followed instructions...

First bug was I needed to `mkdir data` meself.

Next is that, when I navigate to the url in the browser I got this badboy:

```
$ flask --app=src
 * Flask-DebugToolbar: off, Flask-Debug: on
 * Running on http://localhost:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Flask-DebugToolbar: off, Flask-Debug: on
 * Debugger is active!
 * Debugger pin code: 579-418-775
Warning: Permanently added 'james02,129.215.18.52' (ECDSA) to the list of known hosts.
Warning: Permanently added 'james04,129.215.18.54' (ECDSA) to the list of known hosts.
Warning: Permanently added 'james03,129.215.18.53' (ECDSA) to the list of known hosts.
Warning: Permanently added 'james06,129.215.18.56' (ECDSA) to the list of known hosts.
Warning: Permanently added 'james05,129.215.18.55' (ECDSA) to the list of known hosts.
Warning: Permanently added 'james07,129.215.18.57' (ECDSA) to the list of known hosts.
Warning: Permanently added 'james08,129.215.18.58' (ECDSA) to the list of known hosts.
Warning: Permanently added 'james09,129.215.18.59' (ECDSA) to the list of known hosts.
Warning: Permanently added 'james10,129.215.18.60' (ECDSA) to the list of known hosts.
Warning: Permanently added 'james11,129.215.18.61' (ECDSA) to the list of known hosts.
Warning: Permanently added 'james12,129.215.18.62' (ECDSA) to the list of known hosts.
Connection closed by 129.215.18.61
Warning: Permanently added 'james13,129.215.18.63' (ECDSA) to the list of known hosts.
Warning: Permanently added 'james15,129.215.18.65' (ECDSA) to the list of known hosts.
Warning: Permanently added 'james16,129.215.18.66' (ECDSA) to the list of known hosts.
Warning: Permanently added 'james14,129.215.18.64' (ECDSA) to the list of known hosts.
Warning: Permanently added 'james17,129.215.18.67' (ECDSA) to the list of known hosts.
Warning: Permanently added 'james18,129.215.18.68' (ECDSA) to the list of known hosts.
Warning: Permanently added 'james19,129.215.18.69' (ECDSA) to the list of known hosts.
Warning: Permanently added 'james20,129.215.18.70' (ECDSA) to the list of known hosts.
Warning: Permanently added 'james21,129.215.18.71' (ECDSA) to the list of known hosts.
Warning: Permanently added 'charles02,129.215.18.42' (ECDSA) to the list of known hosts.
Warning: Permanently added 'charles03,129.215.18.43' (ECDSA) to the list of known hosts.
Warning: Permanently added 'charles04,129.215.18.44' (ECDSA) to the list of known hosts.
Warning: Permanently added 'charles05,129.215.18.45' (ECDSA) to the list of known hosts.
Warning: Permanently added 'charles06,129.215.18.46' (ECDSA) to the list of known hosts.
Warning: Permanently added 'charles07,129.215.18.47' (ECDSA) to the list of known hosts.
Warning: Permanently added 'charles08,129.215.18.48' (ECDSA) to the list of known hosts.
Warning: Permanently added 'charles09,129.215.18.49' (ECDSA) to the list of known hosts.
Warning: Permanently added 'charles10,129.215.18.50' (ECDSA) to the list of known hosts.
Warning: Permanently added 'mary,129.215.18.72' (ECDSA) to the list of known hosts.
Warning: Permanently added 'staff.compute,129.215.32.3' (RSA) to the list of known hosts.
finger: ganglia: no such user.
127.0.0.1 - - [04/Jun/2016 01:48:56] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/james/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/james/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/james/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/james/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/james/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/james/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/james/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/james/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/james/git/serverwatch/src/frontend.py", line 22, in index
    names = sorted(stats.get_stats().keys())
  File "/home/james/git/serverwatch/src/remote.py", line 297, in get_stats
    self.update_stats()
  File "/home/james/git/serverwatch/src/remote.py", line 274, in update_stats
    self.update_stats_dist()
  File "/home/james/git/serverwatch/src/remote.py", line 267, in update_stats_dist
    self._stats[server_name][self.KEY_CPU] = self._process_cpu_data(result)
  File "/home/james/git/serverwatch/src/remote.py", line 210, in _process_cpu_data
    self._finger_user(parts[self.IDX_TOP_USER]),
  File "/home/james/git/serverwatch/src/remote.py", line 180, in _finger_user
    data = run_popen(cmd_finger).split('\n')[0].split('Name:')[1]
IndexError: list index out of range
127.0.0.1 - - [04/Jun/2016 01:48:57] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [04/Jun/2016 01:48:57] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [04/Jun/2016 01:48:57] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [04/Jun/2016 01:48:57] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
Connection closed by 129.215.18.61
finger: ganglia: no such user.

```

**Comment by mattalexpugh** [comment]
`PATH_DATA` is said as something you need to configure -- not a bug m80

A couple of 'users' popped up lately who have no directory entry. A simple fix could be modifying [this line](https://github.com/cdt-data-science/serverwatch/blob/7d719b7dab560761278a92b85ef84dfaced32983/src/remote.py#L180) -- change to `data = run_popen(cmd_finger)` then probe `data` to see if it's able to be split -- if so, do it, if not, have some default.
